# Generated by Django 5.2.7 on 2025-11-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_purchaseorder_date_remove_supplier_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
