# Generated by Django 5.2.7 on 2025-11-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_purchaseorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
