# Generated by Django 5.2.7 on 2025-11-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_customer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.TextField(blank=True, default=-2001),
            preserve_default=False,
        ),
    ]
