# Generated by Django 5.2.7 on 2025-11-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_supplierpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
