# Generated by Django 5.2.7 on 2025-11-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_supplierpayment_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
