# Generated by Django 5.2.7 on 2025-11-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_purchaseorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='nepal_date',
            field=models.TextField(blank=True),
        ),
    ]
