# Generated by Django 5.2.7 on 2025-11-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_purchaseorder_nepal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='nepal_date',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
