# Generated by Django 5.2.7 on 2025-11-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_purchaseorder_date_alter_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created_at',
        ),
        migrations.AddField(
            model_name='sale',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='nepal_date',
            field=models.TextField(blank=True),
        ),
    ]
