# Generated by Django 5.2.7 on 2025-11-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_sale_options_remove_sale_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
