# Generated by Django 5.2.7 on 2025-11-09 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_customerpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Home', 'Home'), ('salary', 'Salary'), ('Shop', 'Shop'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=50)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('nepal_date', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
