# Generated by Django 5.2.7 on 2025-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('Salary', 'Salary'), ('Shop', 'Shop'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], default='other', max_length=50),
        ),
    ]
