# Generated by Django 5.2.7 on 2025-11-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpayment',
            name='receipt_number',
        ),
    ]
