# Generated by Django 5.2.7 on 2025-11-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_return_returnitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='product_name',
        ),
    ]
